### ISSUE TITLE
"Cookies and session management"

### ISSUE THREAD

**Issue by andreaulicna** [loudapet/42webserv#94]
- [x] Does CGI work with other script? -> Test with a script that prints a website
- [x] Scripts:
  - [x] setCookie - what info do we want (e.g. timeout, limit URL)?
  - [x] getCookie - print info about cookie via CGI, which redirects it to the response
  - [x] session
  - [x] accountCreation - save data in user_database
  - [x] uploadHandler - add from Slack
- [x] Web:
  - [x] Cookies/ session pages: Login page, Dashboard, "Error" page, Logout (delete session ID, bye message -> login page)

**Comment by loudapet** [comment]
both setCookie and getCookie are unprotected (the CGI script crashes with an exception if you input something invalid like [a] as key, or an empty value), so that needs to be handled eventually

**Comment by loudapet** [comment]
I also recommend using a different language for session handling - sending registration data as GET request is dangerous, and we can't handle POSt requests well enough because cgi module is deprecated and there are no official replacements (alternatively, we could just force Eudald to install multipart package, but idk how successful that would be), PHP or JS should probably work
